const WORKS = {
  "II-008-PL-MC":"Monserrat Andrea Ortiz Cortes",
  "II-009-PL-MC":"Castillo Olvera Itzel Jimena",
  "II-010-PL-NT":"Edgar Valeria de la Cruz",
  "II-012-PL-MC":"Marisol Garay Contreras",
  "II-016-PL-NT":"Natalia Valeria Sillerico Illanes",
  "II-020-PL-NT":"Daniela Torres Velasco",
  "II-022-PL-NT":"Astrid Adamari De la Rosa Cordero",
  "II-024-PL-NT":"Sara Gabriela Guadarrama Tovar",
  "II-025-PL-NT":"Astrid Sophia Careaga Arceo",
  "II-027-PL-MC":"Elena Abigail Pérez Ham",
  "II-029-PL-ET":"Fátima Monserrat Ávila Quintero",
  "II-032-PL-NT":"Paz Peña Dana Paola",
  "II-033-PL-ET":"Mariana Berenice López Arenas",
  "II-039-PL-MC":"Ana Camila Ramírez Ortiz",
  "II-043-PL-NT":"Dilan Rodríguez Lagos",
  "II-045-PL-NT":"Arianys Carolina Tovar Escobar",
  "II-048-PL-MC":"Anel Camacho Dorantes",
  "II-050-PL-NT":"Alberto Jaret Mejía Meza",
  "II-051-PL-GE":"Yuleny Cervantes Fosado",
  "II-054-PL-NT":"Monserrat Bracho",
  "II-058-PL-NT":"Xaris López Solís",
  "II-059-PL-NT":"Gillian Yazmín Sosa Maldonado",
  "II-060-PL-GE":"José Julián López Hernández",
  "II-062-PL-NT":"Laura Alessandra Ramírez Vázquez",
  "II-064-PL-NT":"Anayeli Panzo Mayahua",
  "II-066-PL-NT":"Valery Rosales Rojas",
  "II-068-PL-PG":"María Elizabeth Sánchez Romero",
  "II-075-PL-NT":"Negrete Chávez Dalia Isamar",
  "II-076-PL-NT":"Axel Emanuel Moctezuma García",
  "II-086-PL-ET":"Erick Santiago Mendoza Palacios",
  "II-089-PL-ET":"Jessamyn Reyna Crespo Sandoval",
  "II-091-PL-ET":"Joslay Cabrera Caballero",
  "II-094-PL-NT":"Anaya Herrera Vania",
  "II-095-PL-ET":"Merary Jael Diaz Espinoza",
  "II-096-PL-ET":"Nadia Meritxell Vargas Freyre",
  "II-098-PL-NT":"Valeria Yareli Salazar Segura",

  "II-001-PP-NT":"Alexis Alejandro García Rivero",
  "II-002-PP-NT":"Antonio Ávila Guerrero",
  "II-003-PP-NT":"Yara Irene López Dionicio",
  "II-004-PP-NT":"Romina María Valladares Ocampo",
  "II-006-PP-GE":"Juan Pablo González Domínguez",
  "II-007-PP-NT":"Israel Lara Vega",
  "II-011-PP-PG":"Ivonne del Socorro Gutiérrez Ruiz",
  "II-013-PP-GE":"Giselle Barrera Zárate",
  "II-014-PP-GE":"José Luis Marroquín Caratachea",
  "II-015-PP-PG":"Ramón López Ocampo",
  "II-019-PP-ET":"Rogelio Iván Gómez Escobedo",
  "II-023-PP-GE":"Itzel Feria Figueroa",
  "II-036-PP-NT":"Luis José Pinto García",
  "II-044-PP-ET":"Luis Mario Sánchez Palestino",
  "II-047-PP-NT":"Víctor Jesús Escudero Huerta",
  "II-049-PP-ET":"Ernesto Santillán Arcos",
  "II-053-PP-GE":"Sally Silva Castro",
  "II-055-PP-MC":"Angelica Castañeda de la Fuente",
  "II-057-PP-NT":"Goretti Araneth López Villafaña",
  "II-061-PP-NT":"Luis Armando García Pedraza",
  "II-069-PP-NT":"Guillermina Chavaro Francisco",
  "II-070-PP-NT":"María de los Ángeles Rodríguez García",
  "II-072-PP-NT":"Karla Reyes Alvarado",
  "II-081-PP-NT":"Stefany Alamilla Cuellar",
  "II-082-PP-NT":"Marcos Uriel González Pérez",
  "II-083-PP-NT":"Andrea Capaceta Osuna",
  "II-085-PP-NT":"Citlali Gómez Márquez",
  "II-088-PP-MC":"Karen Nayeli Hernández Vázquez",
  "II-092-PP-GE":"Pahola del Carmen Rodríguez Pérez",
  "II-093-PP-NT":"Miguel Andrés Valdés Guevara",
  "II-097-PP-ET":"Lourdes Astrid Serrano Quilantán"
};
